version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saas_php
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_URL: "mysql://root:root@database:3306/starter?serverVersion=5.7.39&charset=utf8mb4"
      MESSENGER_TRANSPORT_DSN: "redis://redis:6379/messages"
      MAILER_DSN: "smtp://mailpit:1025"
      MERCURE_URL: "http://mercure/.well-known/mercure"
      MERCURE_PUBLIC_URL: "http://localhost:1337/.well-known/mercure"
      MERCURE_JWT_SECRET: "nGiMJPUEtnjBYjz+eZHESmZUBQ23AJXyuwtFrj4v4no="
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - database
      - redis
      - mailpit
    networks:
      - saas_network

  database:
    image: mysql:5.7
    platform: linux/amd64
    container_name: saas_database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: starter
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - saas_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: saas_pma
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - saas_network

  nginx:
    image: nginx:alpine
    container_name: saas_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - saas_network

  redis:
    image: redis:7-alpine
    container_name: saas_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - saas_network

  mailpit:
    image: axllent/mailpit
    container_name: saas_mailpit
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP
    networks:
      - saas_network

  mercure:
    image: dunglas/mercure
    container_name: saas_mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'nGiMJPUEtnjBYjz+eZHESmZUBQ23AJXyuwtFrj4v4no='
      MERCURE_SUBSCRIBER_JWT_KEY: 'nGiMJPUEtnjBYjz+eZHESmZUBQ23AJXyuwtFrj4v4no='
      MERCURE_EXTRA_DIRECTIVES: demo
    ports:
      - "1337:80"
    networks:
      - saas_network

volumes:
  redis_data:
  db_data:

networks:
  saas_network:
    driver: bridge
